/* scripts/generate-image-map.ts */
import fs from "node:fs";
import path from "node:path";

type MapOut = Record<string, string[]>;

function die(msg: string): never {
  console.error(msg);
  process.exit(1);
}

function normalizeUrl(url: string): string {
  return url.trim();
}

function isUuid(v: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v.trim());
}

function parseTsv(tsv: string): MapOut {
  const lines = tsv
    .split(/\r?\n/)
    .map((l) => l.trimEnd())
    .filter((l) => l.length > 0);

  if (lines.length < 2) die("TSV har for få linjer.");

  // Forvent header først (men vi tolererer at den ikke matcher 100%)
  const header = lines[0].split("\t").map((c) => c.trim());
  if (header.length < 3) die("Header må ha minst 3 kolonner: Enhet, ResourceCategoryId, Supabase link");

  const out: MapOut = {};
  let currentId: string | null = null;

  for (let i = 1; i < lines.length; i++) {
    const cols = lines[i].split("\t");
    const enhet = (cols[0] ?? "").trim();
    const idRaw = (cols[1] ?? "").trim();
    const urlRaw = (cols[2] ?? "").trim();

    if (!urlRaw) {
      // Noen ganger kan URL havne i kolonne 2 hvis tabellen har ekstra tabber
      // Prøv å finne en URL i resten av kolonnene
      const maybeUrl = cols.slice(1).find((c) => (c ?? "").trim().startsWith("http"));
      if (!maybeUrl) continue;
    }

    const url = normalizeUrl(urlRaw || (cols.slice(1).find((c) => (c ?? "").trim().startsWith("http")) ?? ""));
    if (!url) continue;

    if (idRaw) {
      if (!isUuid(idRaw)) {
        die(`Ugyldig ResourceCategoryId på linje ${i + 1}: "${idRaw}" (Enhet: "${enhet}")`);
      }
      currentId = idRaw;
    } else {
      if (!currentId) {
        die(`Fant rad uten ResourceCategoryId før noen id var satt (linje ${i + 1}, Enhet: "${enhet}")`);
      }
    }

    const id = currentId!;
    if (!out[id]) out[id] = [];
    // Unngå duplikater
    if (!out[id].includes(url)) out[id].push(url);
  }

  return out;
}

function emitTs(map: MapOut): string {
  const entries = Object.entries(map).sort(([a], [b]) => a.localeCompare(b));

  const lines: string[] = [];
  lines.push("/* eslint-disable */");
  lines.push("// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.");
  lines.push("// Generated by scripts/generate-image-map.ts from data/resource-images.tsv");
  lines.push("");
  lines.push("export const GENERATED_RESOURCE_CATEGORY_IMAGES: Record<string, string[]> = {");

  for (const [id, urls] of entries) {
    lines.push(`  "${id}": [`);
    for (const u of urls) {
      lines.push(`    "${u}",`);
    }
    lines.push("  ],");
  }

  lines.push("};");
  lines.push("");

  return lines.join("\n");
}

function main() {
  const root = process.cwd();

  const inPath = path.join(root, "data", "resource-images.tsv");
  const outPath = path.join(root, "lib", "generatedImageMap.ts");

  if (!fs.existsSync(inPath)) {
    die(`Mangler inputfil: ${inPath}\nLag den og lim inn tabellen din (TSV).`);
  }

  const tsv = fs.readFileSync(inPath, "utf8");
  const map = parseTsv(tsv);

  const out = emitTs(map);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out, "utf8");

  console.log(`OK: skrev ${Object.keys(map).length} ResourceCategoryId til ${outPath}`);
}

main();